# Generated by Django 4.1.2 on 2022-11-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante",
            name="nombre",
            field=models.CharField(max_length=60),
        ),
    ]
