# Generated by Django 4.1.3 on 2022-12-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alter_estudiante_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='mat_aprobadas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
